name: web-services
services:
  d1-web:
    build:
      context: ./
    container_name: d1-web
    ports:
    - "3001:3001"
    environment:
    - NODE_ENV=production
    command: npx serve -s ./ -l 3001